# Generated by Django 5.0.6 on 2024-06-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_manufactured_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('inn', models.IntegerField(verbose_name='ИНН')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'контакты',
                'ordering': ('inn',),
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', 'price', 'created_at', 'updated_at'), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
