# Generated by Django 5.0.6 on 2024-06-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_contact_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ava',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='img/products', verbose_name='Аватар'),
        ),
    ]
